---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ include "fullname" . }}-hashring
data:
  hashrings.json: |-
    [
      {
        "endpoints": [
          "127.0.0.1:10901"
        ]
      }
    ]
