apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    #appgw.ingress.kubernetes.io/waf-policy-for-path: {{ .Values.ingress.waf }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "fullname" . }}
              servicePort: 19291