{{- if (include "createObjstoreSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-objstore-secret
  labels: {{- include "labels" . | nindent 4 }}
data:
  objstore.yml: |-
    {{- include "tplValue" (dict "value" .Values.objstoreConfig "context" $) | b64enc | nindent 4 }}
{{ end }}