apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "labels" . | indent 4 }}
  name: {{ include "fullname" . }}
spec:
  ports:
    - name: grpc
      port: 10901
      targetPort: 10901
    - name: http
      port: 10902
      targetPort: 10902
    - name: remote-write
      port: 19291
      targetPort: 19291
  selector:
{{ include "labels" . | indent 4 }}